"""Generates and posts PR comments with threat deltas."""

import json
import logging
import os
from typing import Optional

import httpx

from drift import __version__
from drift.models import AnalysisResult, Severity

logger = logging.getLogger(__name__)

_SEV_ICONS = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH: "🟠",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🔵",
}


def generate_pr_comment(result: AnalysisResult) -> str:
    """Generate Markdown for a GitHub PR comment."""
    delta = result.delta
    if not delta or not delta.has_changes:
        return "## 🔒 Drift Threat Delta\n\n✅ No architectural drift or new threats detected."

    lines = ["## 🔒 Drift Threat Delta\n"]

    # New Threats
    if delta.new_threats:
        lines.extend([
            "### New Threats",
            "| Severity | Confidence | Category | Title | Boundary |",
            "|----------|------------|----------|-------|----------|",
        ])
        # Sort by severity
        sorted_new = sorted(delta.new_threats, key=lambda t: list(Severity).index(t.severity))
        for t in sorted_new:
            icon = _SEV_ICONS[t.severity]
            sev = t.severity.value.upper()
            conf = f"{int(t.confidence * 100)}%"
            lines.append(f"| {icon} {sev} | {conf} | {t.stride_category.value} | {t.title} | {t.boundary} |")
        lines.append("")

    # Mitigated Threats
    if delta.mitigated_threats:
        lines.extend([
            "### Mitigated Threats",
        ])
        for t in delta.mitigated_threats:
            lines.append(f"- ~~{t.title}~~")
        lines.append("")

    # Architecture Changes
    if delta.new_components or delta.removed_components or delta.new_boundaries or delta.removed_boundaries:
        lines.extend([
            "### Architecture Changes",
        ])
        if delta.new_components:
            for c in delta.new_components:
                lines.append(f"- ➕ New component: `{c}`")
        if delta.removed_components:
            for c in delta.removed_components:
                lines.append(f"- ➖ Removed component: `{c}`")
        if delta.new_boundaries:
            for b in delta.new_boundaries:
                lines.append(f"- ➕ New boundary: {b}")
        if delta.removed_boundaries:
            for b in delta.removed_boundaries:
                lines.append(f"- ➖ Removed boundary: {b}")
        lines.append("")

    # AI Enhancements
    if result.ai_enhanced:
        lines.append("> ✨ *Threat context enhanced by AI.*")
        lines.append("")

    lines.append(f"---\n*Generated by [Drift](https://github.com/drift-cli) v{__version__}*")
    
    return "\n".join(lines)


def _get_pr_number() -> Optional[int]:
    """Attempt to get PR number from GitHub Actions environment."""
    event_path = os.environ.get("GITHUB_EVENT_PATH")
    if not event_path:
        return None
        
    try:
        with open(event_path, "r", encoding="utf-8") as f:
            event_data = json.load(f)
            
        # Try pull_request.number first
        pr_data = event_data.get("pull_request")
        if pr_data and "number" in pr_data:
            return pr_data["number"]
            
        # Fallback to top-level number (e.g. issue_comment events)
        if "number" in event_data:
            return event_data["number"]
    except Exception as e:
        logger.warning(f"Could not read GITHUB_EVENT_PATH: {e}")
        
    return None


def post_pr_comment(comment: str) -> bool:
    """Post comment to GitHub PR."""
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")
    pr_number = _get_pr_number()

    if not token or not repo or not pr_number:
        logger.warning("GitHub environment variables missing. Printing comment to stdout instead:")
        print("\n" + comment + "\n")
        return False

    url_base = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    try:
        # Check for existing comment
        resp = httpx.get(url_base, headers=headers)
        resp.raise_for_status()
        comments = resp.json()
        
        existing_id = None
        for c in comments:
            if "🔒 Drift Threat Delta" in c.get("body", ""):
                existing_id = c.get("id")
                break
                
        if existing_id:
            # Update existing
            patch_url = f"https://api.github.com/repos/{repo}/issues/comments/{existing_id}"
            resp = httpx.patch(patch_url, headers=headers, json={"body": comment})
            resp.raise_for_status()
            logger.info("Updated existing Drift PR comment")
        else:
            # Create new
            resp = httpx.post(url_base, headers=headers, json={"body": comment})
            resp.raise_for_status()
            logger.info("Created new Drift PR comment")
            
        return True
    except Exception as e:
        logger.error(f"Failed to post GitHub PR comment: {e}")
        print("\n" + comment + "\n")
        return False


def run_github_mode(result: AnalysisResult) -> None:
    """Orchestrate generating and posting the PR comment."""
    comment = generate_pr_comment(result)
    post_pr_comment(comment)
